[toolchain]
anchor_version = "0.32.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
flex = "GtyEE2qh5wP3Vu2xzft5gDZUpiv4mNpTYk8XaQdqZK97"

[programs.devnet]
flex = "GtyEE2qh5wP3Vu2xzft5gDZUpiv4mNpTYk8XaQdqZK97"

[programs.mainnet]
flex = "GtyEE2qh5wP3Vu2xzft5gDZUpiv4mNpTYk8XaQdqZK97"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test --timeout 30000"
