import { rootNodeFromAnchor, type AnchorIdl } from "@codama/nodes-from-anchor";
import { renderVisitor } from "@codama/renderers-js";
import { createFromRoot, updateInstructionsVisitor } from "codama";
import * as fs from "node:fs";
import * as path from "node:path";

const root = path.resolve(import.meta.dirname, "../..");
const idlPath = path.join(root, "target/idl/flex.json");
const outDir = path.join(root, "packages/flex-solana");

const idl = JSON.parse(fs.readFileSync(idlPath, "utf8")) as AnchorIdl;
const rootNode = rootNodeFromAnchor(idl);
const codama = createFromRoot(rootNode);

// Several instructions have PDA seeds that reference themselves (the Anchor
// IDL encodes `session_key_account.key` as just `session_key_account`). Remove
// the auto-derived default so callers pass the address explicitly.
codama.update(
  updateInstructionsVisitor({
    closeSessionKey: {
      accounts: { sessionKeyAccount: { defaultValue: null } },
    },
    revokeSessionKey: {
      accounts: { sessionKeyAccount: { defaultValue: null } },
    },
    submitAuthorization: {
      accounts: { sessionKey: { defaultValue: null } },
    },
  }),
);

await codama.accept(renderVisitor(outDir));

// Codama's nodes-from-anchor does not handle the IDL "constants" section, so
// we generate the constants file directly from the IDL.
const constants = (idl as Record<string, unknown>).constants as
  | { name: string; type: string; value: string }[]
  | undefined;

if (constants && constants.length > 0) {
  const header = [
    "/**",
    " * This code was AUTOGENERATED from the Anchor IDL.",
    " * Please DO NOT EDIT THIS FILE. Re-run `make generate-client` to update it.",
    " */",
    "",
  ];

  const lines = constants.map((c) => {
    if (c.value.trim() === "") {
      throw new Error(`Constant ${c.name} has empty value`);
    }
    const tsValue = Number(c.value);
    if (!Number.isFinite(tsValue)) {
      throw new Error(`Constant ${c.name} has non-numeric value: ${c.value}`);
    }
    if (!Number.isSafeInteger(tsValue)) {
      throw new Error(
        `Constant ${c.name} exceeds Number.MAX_SAFE_INTEGER: ${c.value}`,
      );
    }
    return `export const ${c.name} = ${tsValue};`;
  });

  const content = [...header, ...lines, ""].join("\n");
  const constantsDir = path.join(outDir, "src", "generated", "constants");
  fs.mkdirSync(constantsDir, { recursive: true });
  fs.writeFileSync(path.join(constantsDir, "index.ts"), content);

  // Add the constants export to the generated index if not already present.
  const generatedIndex = path.join(outDir, "src", "generated", "index.ts");
  const indexContent = fs.readFileSync(generatedIndex, "utf8");
  if (!indexContent.includes('"./constants"')) {
    const updated = indexContent.replace(
      'export * from "./accounts"',
      'export * from "./accounts";\nexport * from "./constants"',
    );
    if (updated === indexContent) {
      throw new Error(
        "Failed to inject constants export: expected Codama-generated pattern 'export * from \"./accounts\"' not found in generated index",
      );
    }
    fs.writeFileSync(generatedIndex, updated);
  }
}
